myblog/blog/urls.py
from django.urls import path

from . import views
app_name = "myblog"
urlpatterns = [
    path("", views.index, name="index"),
    path("article/<int:pk>", views.detail, name="detail"),
    path("archives/<int:year>/<int:month>", views.archives, name="archives"),
    path("category/<int:pk>",views.category,name="category"),
    path("tag/<int:pk>",views.tag,name="tag"),
    path("about",views.about,name="about")
    
]

myblog/comments/urls.py
from django.urls import path
from . import views
app_name = "comments"
urlpatterns = [
    path(
        "comment/article/<int:article_pk>",
        views.article_comment,
        name="article_comment"),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("blog/",include("blog.urls")),
    path('admin/', admin.site.urls),
    path("comments/",include("comments.urls")),
    
]

myblog/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Category(models.Model):
    category_name = models.CharField(max_length=200)

    def __str__(self):
        return self.category_name


class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    def __str__(self):
        return self.tag_name

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    digest = models.CharField(max_length=200, blank=True)
    # 一个文章对应一个分类
    # 一个分类下有多个文章
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])

myblog/comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=255)
    url=models.URLField(blank=True)
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    article=models.ForeignKey("blog.Article",on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

myblog/comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=["name","email","url","text"]
        

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category, Tag
import markdown
from comments.forms import CommentForm
from comments.models import Comment
from django.views.decorators.cache import cache_page
# Create your views here.


@cache_page(60 * 5)
def index(request):
    article_list = Article.objects.all().order_by("-created_time")
    return render(request, "blog/index.html", {
        "article_list": article_list,
    })


@cache_page(60 * 5)
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.increase_views()
    article.body = markdown.markdown(
        article.body,
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    form = CommentForm()
    comment_list = article.comment_set.all()
    context = {
        "article": article,
        "form": form,
        "comment_list": comment_list,
    }
    return render(request, "blog/detail.html", context=context)


@cache_page(60 * 5)
def archives(request, year, month):
    article_list = Article.objects.filter(
        created_time__year=year,
        created_time__month=month).order_by("-created_time")
    return render(request, "blog/index.html", {"article_list": article_list})


@cache_page(60 * 5)
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    article_list = Article.objects.filter(
        category=cate).order_by("-created_time")
    return render(request, "blog/index.html", {"article_list": article_list})


@cache_page(60 * 5)
def tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    article_list = Article.objects.filter(tags=tag).order_by("-created_time")
    return render(request, "blog/index.html", {"article_list": article_list})


@cache_page(60 * 5)
def about(request):
    article_list = Article.objects.all().order_by("-created_time")
    return render(request, "blog/about.html", {
        "article_list": article_list,
    })

myblog/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article
from .models import Comment
from .forms import CommentForm


def article_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            # 调用 article 的 get_absolute_url
            return redirect(article)
        else:
            comment_list = article.comment_set.all()
            context = {
                "article": article,
                "form": form,
                "comment_list": comment_list,
            }
            return render(request, "blog/detail.html", context=context)
    return redirect(article)

myblog/blog/templates/blog/about.html
{%load static%}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{%static 'blog/css/bootstrap.min.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/ionicons.min.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/pace.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/custom.css'%}">

	    <!-- js -->
		<script src="{%static 'blog/js/jquery-2.1.3.min.js'%}"></script>
		<script src="{%static 'blog/js/bootstrap.min.js'%}"></script>
		<script src="{%static 'blog/js/pace.min.js'%}"></script>
		<script src="{%static 'blog/js/modernizr.custom.js'%}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{%url 'myblog:index'%}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{%url 'myblog:index'%}" >主页</a></li>
    								<!-- <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li> -->
    								<li class="cl-effect-11"><a href="{%url 'myblog:about'%}" >关于</a></li>
    								<!-- <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li> -->
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">关于我</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<!-- <figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure> -->
								<p>python Django</p>
								<p>python Django</p>
								<div class="height-40px"></div>
								<!-- <h2 class="title text-center">Social</h2> -->
								<!-- <ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul> -->
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2018 </p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{%static 'blog/js/script.js'%}"></script>
		
	</body>
</html>

myblog/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html>

<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{%static 'blog/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{%static 'blog/css/pace/css'%}">
    <link rel="stylesheet" href="{%static 'blog/css/custom.css'%}">

    <!-- js -->
    <script src="{%static 'blog/js/jquery-2.1.3.min.js'%}"></script>
    <script src="{%static 'blog/js/bootstrap.min.js'%}"></script>
    <script src="{%static 'blog/js/pace.min.js'%}"></script>
    <script src="{%static 'blog/js/modernizr.custom.js'%}"></script>
</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{%url 'myblog:index'%}"><b>Black</b> &amp; White</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{%url 'myblog:index'%}" data-hover="首页">首页</a></li>
                                <!-- <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li> -->
                                <li class="cl-effect-11"><a href="{%url 'myblog:about'%}" data-hover="关于">关于</a></li>
                                <!-- <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li> -->
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <!-- <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div> -->
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
    <div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
                    
                    <!-- <div class="pagination">
                        <ul>
                            <li><a href="">1</a></li>
                            <li><a href="">...</a></li>
                            <li><a href="">4</a></li>
                            <li><a href="">5</a></li>
                            <li ><a href="">6</a></li>
                            <li><a href="">7</a></li>
                            <li><a href="">8</a></li>
                            <li><a href="">...</a></li>
                            <li><a href="">11</a></li>
                        </ul>
                    </div> -->

                </main>
                <aside class="col-md-4">
                    {% block toc%}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3>
                        <ul>
                            {%for article in article_list%}
                            <li>
                                <a href="{{article.get_absolute_url}}">{{article.title}}</a>
                            </li>
                            {%empty%}
                            暂无文章
                            {%endfor%}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        {% archives as date_list%}
                        <ul>
                            {%for date in date_list%}
                            <li>
                                <a href="{%url 'myblog:archives' date.year date.month%}">{{date.year}}年{{date.month}}月</a>
                            </li>
                            {%empty%}
                            暂无归档
                            {%endfor%}
                        </ul>
                    </div>
                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        {% get_categories as category_list%}
                        <ul>
                            {%for category in category_list %}
                            <li>
                                <a href="{% url 'myblog:category' category.pk %}">{{category}}</a>
                            </li>
                            {%empty%}
                            暂无分类
                            {%endfor%}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        {% get_tags as tag_list%}
                        <ul>
                            {%for tag in tag_list%}

                            <li><a href="{%url 'myblog:tag' tag.pk%}">{{tag}}</a></li>
                            {%empty%}
                            暂无标签
                            {%endfor%}
                        </ul>
                    </div>
                    <!-- <div class="rss">
                        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div> -->
                    {%endblock toc%}
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2018 
                            
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="index.html">首页</a></li>
                <li><a href="#">博客</a></li>
                <li><a href="#">关于</a></li>
                <li><a href="#">联系</a></li>
            </ul>
        </nav>
    </div>

    <script src="{%static 'blog/js/script.js'%}"></script>

</body>

</html>

myblog/blog/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{%static 'blog/css/bootstrap.min.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/ionicons.min.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/pace.css'%}">
		<link rel="stylesheet" href="{%static 'blog/css/custom.css'%}">

	    <!-- js -->
		<script src="{%static 'blog/js/jquery-2.1.3.min.js'%}"></script>
		<script src="{%static 'blog/js/bootstrap.min.js'%}"></script>
		<script src="{%static 'blog/js/pace.min.js'%}"></script>
		<script src="{%static 'blog/js/modernizr.custom.js'%}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{%static 'blog/js/script.js'%}"></script>
		
	</body>
</html>

myblog/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block main %}
<article class="article article-{{article.pk}}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="#">{{ article.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="article-category">
                <a href="#">{{article.category}}</a>
            </span>
            
            <span class="article-date">
                <a href="#">
                    <time class="entry-date" datetime="{{article.created_time}}">{{article.created_time}}</time>
                </a>
            </span>
            <span class="article-author">
                <a href="#">{{article.author}}</a>
            </span>
            <span class="comments-link">
                <a href="#">{{comment_list.count}}评论</a>
            </span>
            <span class="views-count">
                <a href="#">{{article.views}}阅读</a>
            </span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{article.body|safe}}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{%url 'comments:article_comment' article.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{form.name.id_for_label}}">名字：</label>
                {{form.name}}
                {{form.name.error}}
            </div>
            <div class="col-md-4">
                <label for="{{form.email.id_for_label}}">邮箱：</label>
                {{form.email}}
                {{form.email.error}}
            </div>
            <div class="col-md-4">
                <label for="{{form.url.id_for_label}}">网址：</label>
                {{form.url}}
                {{form.url.error}}
            </div>
            <div class="col-md-12">
                <label for="{{form.text.id_for_label}}">评论：</label>
                {{form.text}}
                {{form.text.error}}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{comment_list.count}}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {%for comment in comment_list%}
            <li class="comment-item">
                <span class="nickname">{{comment.name}}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.created_time}}</time>
                <div class="text">
                    {{comment.text}}
                </div>
            </li>
            {%empty%}
            暂无评论
            {%endfor %}
        </ul>
    </div>
</section>
{% endblock main %}

{% block toc %}
<!-- <div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    <ul>
        <li> <a href="#">教程特点</a> </li>
        <li> <a href="#">谁适合这个教程</a> </li>
        <li> <a href="#">在线预览</a> </li>
        <li> <a href="#">资源列表</a> </li>
        <li> <a href="#">获取帮助</a> </li>
    </ul>
</div> -->
{% endblock toc %}

myblog/blog/templates/blog/full-width.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html>

<head>
	<title>Black &amp; White</title>

	<!-- meta -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- css -->
	<link rel="stylesheet" href="{%static 'blog/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<link rel="stylesheet" href="{%static 'blog/css/pace/css'%}">
	<link rel="stylesheet" href="{%static 'blog/css/custom.css'%}">

	<!-- js -->
	<script src="{%static 'blog/js/jquery-2.1.3.min.js'%}"></script>
	<script src="{%static 'blog/js/bootstrap.min.js'%}"></script>
	<script src="{%static 'blog/js/pace.min.js'%}"></script>
	<script src="{%static 'blog/js/modernizr.custom.js'%}"></script>
</head>

<body>
	<div class="container">
		<header id="site-header">
			<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
					<div class="logo">
						<h1><a href="{%url 'myblog:index'%}"><b>Black</b> &amp; White</a></h1>
					</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
					<nav class="main-nav" role="navigation">
						<div class="navbar-header">
							<button type="button" id="trigger-overlay" class="navbar-toggle">
								<span class="ion-navicon"></span>
							</button>
						</div>

						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav navbar-right">
								<li class="cl-effect-11"><a href="{%url 'myblog:index'%}" data-hover="首页">首页</a></li>
								<li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
								<li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
								<li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
							</ul>
						</div><!-- /.navbar-collapse -->
					</nav>
					<div id="header-search-box">
						<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
						<div id="search-form" class="search-form">
							<form role="search" method="get" id="searchform" action="#">
								<input type="search" placeholder="搜索" required>
								<button type="submit"><span class="ion-ios-search-strong"></span></button>
							</form>
						</div>
					</div>
				</div><!-- col-md-8 -->
			</div>
		</header>
	</div>
	<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
	<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

	<div class="content-body">
		<div class="container">
			<div class="row">
				<main class="col-md-8">
					{% block main %}
					{% endblock main %}

					<div class="pagination">
						<ul>
							<li><a href="">1</a></li>
							<li><a href="">...</a></li>
							<li><a href="">4</a></li>
							<li><a href="">5</a></li>
							<li class="current"><a href="">6</a></li>
							<li><a href="">7</a></li>
							<li><a href="">8</a></li>
							<li><a href="">...</a></li>
							<li><a href="">11</a></li>
						</ul>
					</div>

				</main>
				<aside class="col-md-4">
					{% block toc%}
					<div class="widget widget-recent-posts">
						<h3 class="widget-title">最新文章</h3>
						<ul>
							{%for article in article_list%}
							<li>
								<a href="{{article.get_absolute_url}}">{{article.title}}</a>
							</li>
							{%empty%}
							暂无文章
							{%endfor%}
						</ul>
					</div>
					<div class="widget widget-archives">
						<h3 class="widget-title">归档</h3>
						{% archives as date_list%}
						<ul>
							{%for date in date_list%}
							<li>
								<a href="{%url 'myblog:archives' date.year date.month%}">{{date.year}}年{{date.month}}月</a>
							</li>
							{%empty%}
							暂无归档
							{%endfor%}
						</ul>
					</div>
					<div class="widget widget-category">
						<h3 class="widget-title">分类</h3>
						{% get_categories as category_list%}
						<ul>
							{%for category in category_list %}
							<li>
								<a href="{% url 'myblog:category' category.pk %}">{{category}}</a>
							</li>
							{%empty%}
							暂无分类
							{%endfor%}
						</ul>
					</div>

					<div class="widget widget-tag-cloud">
						<h3 class="widget-title">标签云</h3>
						{% get_tags as tag_list%}
						<ul>
							{%for tag in tag_list%}

							<li><a href="{%url 'myblog:tag' tag.pk%}">{{tag}}</a></li>
							{%empty%}
							暂无标签
							{%endfor%}
						</ul>
					</div>
					<div class="rss">
						<a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
					</div>
					{%endblock toc%}
				</aside>
			</div>
		</div>
	</div>
	<footer id="site-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p class="copyright">&copy 2018

					</p>
				</div>
			</div>
		</div>
	</footer>

	<!-- Mobile Menu -->
	<div class="overlay overlay-hugeinc">
		<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
		<nav>
			<ul>
				<li><a href="index.html">首页</a></li>
				<li><a href="#">博客</a></li>
				<li><a href="#">关于</a></li>
				<li><a href="#">联系</a></li>
			</ul>
		</nav>
	</div>

	<script src="{%static 'blog/js/script.js'%}"></script>

</body>

</html>